### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by A5H1Q** [A5H1Q/Inventory-control-system#1]
[sample1](https://codeofaninja.com/2014/06/php-object-oriented-crud-example-oop.html)

**Comment by Ebinu-S** [comment]
[Pen 1, FEND](https://codepen.io/markmurray/details/aCfiF)

**Comment by Ebinu-S** [comment]
[Glass-FND](https://codepen.io/dasshounak/pen/QWKKYdj)
[Task1 - FND](https://codepen.io/younes-el-mansouri/pen/bGwmPrK)
[Theme - FND](https://codepen.io/MoustafaJazzar/pen/poENwVV)
[Contact - FND](https://codepen.io/jaycbrf/details/iBszr)
[base1 - FND](https://codepen.io/aybukeceylan/details/OJRNbZp)
[base2 - FND](https://codepen.io/TurkAysenur/details/NWRqoyL)

**Comment by A5H1Q** [comment]
Noice

**Comment by A5H1Q** [comment]
- sql dump uploaded.  
   db name: inv  

- import  inv.sql to generate tables

**Comment by Ebinu-S** [comment]
ok.
